# Generated by Django 3.0.5 on 2022-01-24 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('access_register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='ip_user',
        ),
        migrations.AddField(
            model_name='news',
            name='lead',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
