# Generated by Django 3.0.5 on 2022-01-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_register', '0002_auto_20220124_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hash',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='txId',
            field=models.CharField(default=None, max_length=66, null=True),
        ),
    ]
