# Generated by Django 3.0.5 on 2022-02-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_register', '0004_loggeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_idSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleIdCode', models.IntegerField()),
                ('typeOutJson', models.CharField(default='HTML', max_length=4)),
            ],
        ),
    ]
