# Generated by Django 3.0.5 on 2022-02-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_register', '0005_type_idsearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='lead',
            new_name='titolo',
        ),
    ]
