# Generated by Django 3.0.5 on 2022-02-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_register', '0006_auto_20220217_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='titolo',
            new_name='title',
        ),
    ]
