# Generated by Django 3.0.5 on 2022-02-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_register', '0007_auto_20220217_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_idUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journalistId', models.IntegerField()),
            ],
        ),
    ]
